### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by ianacaburian** [ianacaburian/core#3]
### Parallel Tasks
- [Set up project-template CI](https://github.com/ianacaburian/ssm-project-template/issues/1).

### Tasks
- [x] Build SmokeTests for modules with test utils.
- [x] Cache variable options.
- [x] CMakePresets files.
- [x] Add linters.
- [x] Fix all build warnings/errors.
- [x] Build Actions workflow.
- [x] Activate repo badges.
