### ISSUE TITLE
Replace ssm_tools.

### ISSUE THREAD

**Issue by ianacaburian** [ianacaburian/core#4]
### Tasks
- [ ] Replace ssm_tools in all consuming apps.
- [ ] Ensure consuming apps pass builds and tests.
- [ ] Delete ssm_tools repo.
