### ISSUE TITLE
Create CMake Utilities

### ISSUE THREAD

**Issue by ianacaburian** [ianacaburian/core#7]
## Tasks
- [x] Linters with Xcode Schemes for running Ninja targets.
- [x] PluginVal
  - [x] Source repo via CPM with options:
    - "DOWNLOAD_ONLY YES"
    - "EXCLUDE_FROM_ALL YES"
    - "SYSTEM NO"
    - OPTIONS empty.
  - [x] Build binary in config phase via `execute_process().
    - [x] Configure with options (as per pluginval repo):
      - "CMAKE_BUILD_TYPE Debug" (for breakpoint debugging on failed validations).
      - "PLUGINVAL_FETCH_JUCE ON" is required when CPM source caching is enabled.
  - [x] Tester target per plugin project (not top-level):
    - [x] Project name is part of target name: ${PROJECT_NAME}_PluginVal.
    - [x] Uses the pluginval.app located at top-level to test each plugin project's VST3 target.
- [x] `juce_add_plugin()` related utilities.
- [x] Test related utilities.
  - [x] Catch2TestRunner.

## Finishing
- [x] Change license to GPL3
- [x] Uninstall nix & conan
