### ISSUE TITLE
Basic Packaging

### ISSUE THREAD

**Issue by ianacaburian** [ianacaburian/core#8]
## Exploratory
- [x] Explore repos that package juce modules and cmake utils for guidance.
  - [JUCE CMakeLists.txt](https://github.com/juce-framework/JUCE/blob/master/CMakeLists.txt)
  - [chowdsp_utils AddJUCEModules.cmake](https://github.com/Chowdhury-DSP/chowdsp_utils/blob/master/cmake/AddJUCEModules.cmake)
  - [Oranges CMakeLists.txt](https://github.com/benthevining/Oranges/blob/main/CMakeLists.txt).

## Tasks
- [x] Package repo for consumption via `add_subdirectory()` (support `find_package()` in the future).
  - [x] Available package content:
    - [x] CMake modules.
    - [x] JUCE modules in ssm_tools.
  - [x] CMake modules are automatically included.
  - [x] Add CPM and JUCE dependency for reuse by consumers.
- [x] Create core_project_template to demo/test core package.

## Test
- [x] Consume package in another project:
  - [x] Add package with CPM.
  - [x] Test CMake modules.
  - [x] Test JUCE modules.
  - [x] Test transitive dependency management by CPM:
    - [x] Clear CPM cache and observe configuring consumer project with CPM and JUCE added as a dependency (as if unaware that the core package has these dependencies added already).
